### PR TITLE
Fix bundle import/export

### LINKED ISSUE #1937: Importing an exported bundle fails with an error
I am currently using the current juju beta: `2.0-beta15-xenial-amd64`. I have a bundle which I have exported using the juju gui and not modified which is can be found here: [default-2016-08-16.txt](https://github.com/juju/juju-gui/files/425430/default-2016-08-16.txt). When I attempt to import this bundle back into the juju gui I get the following error:

    The following errors occurred while retrieving bundle changes: cannot read bundle YAML: 
    cannot unmarshal bundle data: yaml: unmarshal errors: line 1: cannot unmarshal !!str 
    `xenial` into charm.legacyBundleData

I am able to reorder the contents of the yaml file and then get it to import, however attempting to import in the order which it was originally exported fails.

### PR DESCRIPTION
**Pull request by huwshimi**
There are two issues addressed here. Firstly fixes importing bundles files using the new yaml format using 'applications' instead of 'services' and also resolves exporting bundles with availability-zone constraints. Fixes #1937.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- load the gui using juju 2
- drop a simple model file e.g.

```
series: trusty
applications: 
  apache2: 
    charm: "cs:trusty/apache2-20"
    num_units: 1
    to: 
      - "0"
  mysql: 
    charm: "cs:trusty/mysql-20"
    num_units: 1
    annotations: 
      "gui-x": 525.4590454101562
      "gui-y": 667.7398071289062
    to: 
      - "1"
  wordpress: 
    charm: "cs:trusty/wordpress-4"
    num_units: 1
    to: 
      - "2"
relations: 
  - - "wordpress:db"
    - "mysql:db"
  - - "apache2:reverseproxy"
    - "wordpress:website"
machines: 
  "0": 
    series: trusty
    constraints: "arch=amd64 cpu-cores=1 cpu-power=100 mem=1740 root-disk=8192"
  "1": 
    series: trusty
    constraints: "arch=amd64 cpu-cores=1 cpu-power=100 mem=1740 root-disk=8192"
  "2": 
    series: trusty
    constraints: "arch=amd64 cpu-cores=1 cpu-power=100 mem=1740 root-disk=8192"
```
- there should be no errors
- deploy
- export the model
- open the file
- you should not see any constraints like `undefined=default` instead you should see `availability-zone=...`

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5655/
Test PASSed.

**Comment by anthonydillon** [comment]
Code looks good :+1: thanks.

**Comment by bac** [comment]
I did the QA and the bundle imported just fine. But when I exported I didn't see any `undefined` settings but also didn't see the availability-zone you mention. This was on LXD so perhaps that's the reasons?

Here is the exported bundle:

```
series: xenial
applications: 
  apache2: 
    charm: "cs:trusty/apache2-20"
    num_units: 1
    annotations: 
      "gui-x": "300"
      "gui-y": "300"
    to: 
      - "1"
  mysql: 
    charm: "cs:trusty/mysql-20"
    num_units: 1
    annotations: 
      "gui-x": "525.4590454101562"
      "gui-y": "667.7398071289062"
    to: 
      - "2"
  wordpress: 
    charm: "cs:trusty/wordpress-4"
    num_units: 1
    annotations: 
      "gui-x": "600"
      "gui-y": "300"
    to: 
      - "0"
relations: 
  - - "wordpress:db"
    - "mysql:db"
  - - "apache2:reverseproxy"
    - "wordpress:website"
machines: 
  "0": 
    series: trusty
    constraints: arch=amd64
  "1": 
    series: trusty
    constraints: arch=amd64
  "2": 
    series: trusty
    constraints: arch=amd64
```

**Comment by bac** [comment]
Marking as QA-OK. Please change if you think the above is wrong.

File: jujugui/static/gui/src/app/models/models.js [hunk 1]
```diff
@@ -2713,16 +2713,16 @@ YUI.add('juju-models', function(Y) {
     _collapseMachineConstraints: function(constraints) {
       var constraint = '';
       var constraintMap = {
-        arch: 'arch',
+        availabilityZone: 'availability-zone',
         cpuCores: 'cpu-cores',
         cpuPower: 'cpu-power',
-        mem: 'mem',
         disk: 'root-disk'
```
Comment (bac) [inline jujugui/static/gui/src/app/models/models.js]: Why are we dropping mem and arch support?

Comment (hatched) [inline jujugui/static/gui/src/app/models/models.js]: @bac the `constraintMap` is a map to fix the constraints which use a different format than Juju expects, ex ) cpuCores > cpu-cores

Comment (bac) [inline jujugui/static/gui/src/app/models/models.js]: Oh, ok, I thought it was a list of supported constraints.  That might be a nice place for a comment, since it was previously being used wrong.

**Comment by hatched** [comment]
Thanks @huwshimi This looks great.

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge
