### PR TITLE
Fix Juju 1.25 console errors.

### LINKED ISSUE #1974: Juju 1.25 console errors
When logging in:
- Uncaught TypeError: Cannot read property 'setCredentials' of undefined
 - This is caused by https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/app.js#L857 sometimes getting passed an undefined value for an api. This is unavoidable so this loop simply needs to check if `api` is undefined and if so then continue on the loop.

- Warning: Failed prop type: Required prop `listModels` was not specified in 'Constructor'. in Constructor
 - It looks like we have `listModels` listed as a required prop in the model switcher but in Juju 1 we do not have list models support.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #1974.

### CODE REVIEW

File: jujugui/static/gui/src/app/app.js [hunk 1]
```diff
@@ -845,20 +845,24 @@ YUI.add('juju-gui', function(Y) {
       credentials, useMacaroons, apis=[this.env, this.controllerAPI]) {
       if (useMacaroons) {
         apis.forEach(api => {
-          api.loginWithMacaroon(new Y.juju.environments.web.Bakery({
-            webhandler: new Y.juju.environments.web.WebHandler(),
-            interactive: true,
-            serviceName: 'juju',
-            dischargeStore: window.localStorage
-          }), this._apiLoginHandler.bind(this, api));
+          if (api) {
```
Comment (hatched) [inline jujugui/static/gui/src/app/app.js]: Could you add some comments here as to why there might not be an api

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5752/
Test PASSed.

File: jujugui/static/gui/src/app/app.js (hunk 1 above)
Comment (hatched) [inline jujugui/static/gui/src/app/app.js]: It's possible that this method is called without specifying the apis. At which point the default values are used. It is however possible at that point that there is no controllerAPI instance because we are in a Juju model which does not support it. This causes the apis array to be `[this.env, undefined]` causing the login's to fail.

**Comment by hatched** [comment]
QA O K !

**Comment by kadams54** [comment]
Per @hatched and I QAing in both Juju 1 & Juju 2, it looks good so... :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5753/
Test PASSed.
