### PR TITLE
Fix mask shadow offset on charm icon

### LINKED ISSUE #1322: Charm icon masks are offset by one or two pixels in firefox/Chrome
juju_admin

### PR DESCRIPTION
**Pull request by anthonydillon**
Fixes #1322

### CODE REVIEW

**Comment by anthonydillon** [comment]
## QA
 - Check this resolves the https://github.com/juju/juju-gui/issues/1322

File: jujugui/static/gui/src/app/views/topology/topology.js [hunk 1]
```diff
@@ -190,6 +190,27 @@ YUI.add('juju-topology', function(Y) {
...
+
+      var clip = vis.append('clipPath')
+        .attr({
+          id: function(d) { return 'clip-mask'; },
+        });
+
+      clip.append('use')
+        .attr({
+          'xlink:href': function(d) { return '#service-icon-mask'; }
+        });
```
Comment (anthonydillon) [inline jujugui/static/gui/src/app/views/topology/topology.js]: Moved the service mask to a global mask which is reused by all charm services instead of having the same mask duplicated inside each service.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4343/
Test FAILed.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4344/
Test FAILed.

**Comment by anthonydillon** [comment]
Manual CI build passed: http://ci.jujugui.org:8080/job/juju-gui/4345/w

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4346/
Test PASSed.

**Comment by huwshimi** [comment]
This looks good with the radius fix changed to 43 as discussed. Thanks @anthonydillon!

**Comment by huwshimi** [comment]
Additionally this now needs to be fixed in the machine view.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4354/
Test PASSed.

File: jujugui/static/gui/src/app/assets/css/_mixins.scss [hunk 2]
```diff
@@ -205,3 +205,13 @@ button,
...
 }
+
+%icon--small {
+    $size: 24px;
+    width: $size;
+    height: $size;
+    vertical-align: middle;
+    text-align: center;
+    -webkit-clip-path: circle(($size / 2 - 1) at center);
+    clip-path: circle(($size / 2 - 1) at center);
```
Comment (huwshimi) [inline jujugui/static/gui/src/app/assets/css/_mixins.scss]: Unfortunately this does not appear to be working in Firefox.

**Comment by huwshimi** [comment]
:+1:!

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4377/
Test FAILed.

**Comment by makyo** [comment]
:+1:

**Comment by anthonydillon** [comment]
Successful run: http://ci.jujugui.org:8080/job/juju-gui/4381

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/4383/
Test FAILed.

**Comment by anthonydillon** [comment]
Thanks :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge
