### PR TITLE
Terminal to handle unexpected disconnect

### LINKED ISSUE #3343: The GUI should react to jujushell socket disconnections
i.e. when the websocket is closed by the server, we should close the terminal and display an error

### PR DESCRIPTION
**Pull request by hatched**
Fixes #3343 

When the terminals websocket connection is unexpectedly disconnected then show an error notification.

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Bootstrap your own controller and deploy and expose the jujushell charm.
Once it is up and running, open the terminal and wait until you get a prompt.
Now unexpose the charm and you should get an error notification about the connection being terminated.

#### Notes 
- You will also get an error about the charm not being exposed and the terminal will close. This will not be the case in the event the server actually closes the connection.
- If you try and simulate a network loss by turning off wifi it will take some time before the websocket is closed by the browser and the terminal will become unresponsive at this time and no notification will be shown until the websocket is closed by the browser.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8287/

File: jujugui/static/gui/src/app/components/terminal/terminal.js [hunk 1]
```diff
@@ -112,6 +112,17 @@ class Terminal extends React.Component {
         term.writeln('connected to temporary workspace.\n');
       }
     };
+    ws.onclose = evt => {
+      if (evt && evt.code > 1000) {
```
Comment (frankban) [inline jujugui/static/gui/src/app/components/terminal/terminal.js]: What about the 1000 special number? Please add a comment.

File: jujugui/static/gui/src/app/components/terminal/terminal.js [hunk 2]
```diff
@@ -112,6 +112,17 @@ class Terminal extends React.Component {
...
+        // It is not a normal closure so we should issue an error.
+        console.log(evt);
```
Comment (frankban) [inline jujugui/static/gui/src/app/components/terminal/terminal.js]: console.error?

File: jujugui/static/gui/src/app/components/terminal/test-terminal.js [hunk 3]
```diff
@@ -146,6 +146,34 @@ describe('Terminal', () => {
     }]);
   });
 
+  it('handles unexpected websocket closures', () => {
```
Comment (frankban) [inline jujugui/static/gui/src/app/components/terminal/test-terminal.js]: s/websocket/WebSocket/ [shrug]

File: jujugui/static/gui/src/app/components/terminal/terminal.js (hunk 1 above)
Comment (hatched) [reply jujugui/static/gui/src/app/components/terminal/terminal.js]: The comment is right below this line ;) I'll make it more explicit.

File: jujugui/static/gui/src/app/components/terminal/terminal.js (hunk 2 above)
Comment (hatched) [reply jujugui/static/gui/src/app/components/terminal/terminal.js]: sure

File: jujugui/static/gui/src/app/components/terminal/test-terminal.js (hunk 3 above)
Comment (hatched) [reply jujugui/static/gui/src/app/components/terminal/test-terminal.js]: done

**Comment by hatched** [comment]
Thanks for the review!

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8293/

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge/2600

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-gce.jujugui.org:8080//job/juju-gui/8294/

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge/2601

**Comment by hatched** [comment]
:shipit: 

Third time is the charm...

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge
