### PR TITLE
Prevent superfluous RPC calls

### LINKED ISSUE #2382: Removing unit before committing makes RPC call
To reproduce, add Kibana to the canvas. Go to the inspector and remove the unit. See it try and make the RPC call.

`api client: operation not supported: {"type":"Client","request":"Resolved","params":{"unit-name":"50435346$/0","retry":false}}`

### PR DESCRIPTION
**Pull request by makyo**
Fixes #2382

### CODE REVIEW

**Comment by makyo** [comment]
# QA

* Get the GUI up and running and connected to a controller. 
* Create a service on a new canvas without committing.
* Switch to the unit list in the inspector.
* Check (don't click) the unit, then click remove.
* Console logs should show no RPC calls.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7361/

File: jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js [hunk 1]
```diff
@@ -441,6 +441,49 @@ describe('UnitList', () => {
...
+    var button = testUtils.findRenderedDOMComponentWithClass(
+        output, 'button--neutral');
+    testUtils.Simulate.click(button);
+    assert.equal(destroyUnits.callCount, 1);
+    assert.deepEqual(destroyUnits.args[0][0], [units[0].id, units[2].id]);
+    // Make sure we mark the unit as resolved so that we can remove it.
+    assert.equal(envResolved.callCount, 2);
+  });
+
+  it('won\'t remove pending units', function() {
```
Comment (jaycee) [inline jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js]: Minor sticking point: How about "will not" instead of the escaped quote? For whatever reason those look weird to me. :stuck_out_tongue_closed_eyes:

File: jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js [hunk 2]
```diff
@@ -469,10 +512,11 @@ describe('UnitList', () => {
     var button = testUtils.findRenderedDOMComponentWithClass(
         output, 'button--neutral');
     testUtils.Simulate.click(button);
+    // Remove is still called to remove from ECS.
     assert.equal(destroyUnits.callCount, 1);
     assert.deepEqual(destroyUnits.args[0][0], [units[0].id, units[2].id]);
     // Make sure we mark the unit as resolved so that we can remove it.
```
Comment (jaycee) [inline jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js]: I think this comment is a leftover? No units get resolved, right?

File: jujugui/static/gui/src/app/components/inspector/unit-list/unit-list.js [hunk 3]
```diff
@@ -125,14 +125,21 @@ YUI.add('unit-list', function() {
...
+      const envResolved = this.props.envResolved;
       Object.keys(refs).forEach(function (ref) {
-        var isInstance = ref.split('-')[0] === 'CheckListItem';
+        let isInstance = ref.split('-')[0] === 'CheckListItem';
         if (isInstance && refs[ref].state.checked) {
-          var unitName = ref.slice(ref.indexOf('-') + 1);
-          units.push(unitName);
+          let unitName = ref.slice(ref.indexOf('-') + 1);
+          unitNames.push(unitName);
+          const unit = units.filter((u) => {
```
Comment (hatched) [inline jujugui/static/gui/src/app/components/inspector/unit-list/unit-list.js]: So you're looping through all the units here and then checking the `agent_status` of one of them with the same id? This will loop through ever unit so this should be more efficient:

```JavaScript
const unit = units.find(u => u.id === unitName);
```

File: jujugui/static/gui/src/app/components/inspector/unit-list/unit-list.js [hunk 4]
```diff
@@ -125,14 +125,21 @@ YUI.add('unit-list', function() {
...
+            return u.id == unitName;
+          })[0];
+          if (!unit.agent_status) {
```
Comment (hatched) [inline jujugui/static/gui/src/app/components/inspector/unit-list/unit-list.js]: I'm assuming that the rational behind not creating a db method for this is because we don't have access to the unit list model. So can you add a code comment as to why this is necessary as it's super cryptic.

File: jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js [hunk 5]
```diff
@@ -441,6 +441,49 @@ describe('UnitList', () => {
...
+      displayName: 'mysql/1',
+      id: 'mysql/1',
+      agent_status: 'running'
+    }, {
+      displayName: 'mysql/2',
+      id: 'mysql/2',
+      agent_status: 'running'
+    }];
+    // Have to use renderIntoDocument here as shallowRenderer does not support
+    // refs.
```
Comment (hatched) [inline jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js]: You _could_ 'hack' the refs into the instance object, but this is better ;)

File: jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js [hunk 6]
```diff
@@ -441,6 +441,49 @@ describe('UnitList', () => {
...
+        output, 'button--neutral');
+    testUtils.Simulate.click(button);
+    assert.equal(destroyUnits.callCount, 1);
+    assert.deepEqual(destroyUnits.args[0][0], [units[0].id, units[2].id]);
+    // Make sure we mark the unit as resolved so that we can remove it.
+    assert.equal(envResolved.callCount, 2);
+  });
+
+  it('won\'t remove pending units', function() {
+    var destroyUnits = sinon.stub();
```
Comment (hatched) [inline jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js]: No new `var`s please

File: jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js (hunk 1 above)
Comment (hatched) [inline jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js]: We definitely still want pending units to be removable. I think it's just the test name "does not create network request to remove uncommitted units"

File: jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js [hunk 7]
```diff
@@ -469,10 +512,11 @@ describe('UnitList', () => {
     var button = testUtils.findRenderedDOMComponentWithClass(
         output, 'button--neutral');
     testUtils.Simulate.click(button);
+    // Remove is still called to remove from ECS.
     assert.equal(destroyUnits.callCount, 1);
     assert.deepEqual(destroyUnits.args[0][0], [units[0].id, units[2].id]);
     // Make sure we mark the unit as resolved so that we can remove it.
-    assert.equal(envResolved.callCount, 2);
+    assert.equal(envResolved.callCount, 0);
```
Comment (hatched) [inline jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js]: So did we have a test for this but the test was wrong?

File: jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js (hunk 2 above)
Comment (makyo) [inline jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js]: *Committed* units still get resolved. I'll expand on that.

File: jujugui/static/gui/src/app/components/inspector/unit-list/unit-list.js (hunk 3 above)
Comment (makyo) [inline jujugui/static/gui/src/app/components/inspector/unit-list/unit-list.js]: Ah, forgot about `find`, ty

File: jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js (hunk 5 above)
Comment (makyo) [inline jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js]: It *is* better.

File: jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js (hunk 7 above)
Comment (makyo) [inline jujugui/static/gui/src/app/components/inspector/unit-list/test-unit-list.js]: We were still making the calls in the test, but the API was stubbed, so this didn't show itself.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7373/

**Comment by jaycee** [comment]
QA notes:

I followed the instructions and saw no RPC calls being made.

Removing commited units worked as expected.

QA OK.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/7374/

**Comment by makyo** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge
