### PR TITLE
Fix the syncing of the environment name in the deployment flow

### LINKED ISSUE #2470: In DF when I give the model a name the breadcrumb in the upper left should sync with that.
@hatched says it should do that and it's a regression.

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2470

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- create a new model
- note that in the canvas header the model name is "untitled-model"
- add an app
- open the deployment flow
- change the model name
- check that on blur the model name in the df header changes
- close the df
- check that the model name in the canvas header has changed
- open the df
- check that the header and model name field contain the new value

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6801/

File: jujugui/static/gui/src/app/app.js [hunk 1]
```diff
@@ -1230,7 +1230,8 @@ YUI.add('juju-gui', function(Y) {
       const env = this.env;
       const db = this.db;
       const connected = this.env.get('connected');
-      const modelName = connected ? db.environment.get('name') : 'mymodel';
+      const environmentName = env.get('environmentName')
+      const modelName = environmentName ? environmentName : 'mymodel';
```
Comment (frankban) [inline jujugui/static/gui/src/app/app.js]: Why not just `const modelName = env.get('environmentName') || 'mymodel';`?
Let's not reintroduce the "environment" to mean "model" please.

File: jujugui/static/gui/src/app/app.js [hunk 2]
```diff
@@ -1300,7 +1301,7 @@ YUI.add('juju-gui', function(Y) {
           changes={currentChangeSet}
           charmsGetById={db.charms.getById.bind(db.charms)}
           deploy={utils.deploy.bind(utils, this)}
-          environment={db.environment}
+          env={env}
```
Comment (frankban) [inline jujugui/static/gui/src/app/app.js]: This should be called model.
Also, we are passing a whole model connection to a component, just to be able to set the environmentName attribute. What do you think about 
```
setModelName={env.set.bind(env, 'environmentName')}
```
Or similar? So that the component can just call the given callable passing the model name.

File: jujugui/static/gui/src/app/app.js (hunk 1 above)
Comment (huwshimi) [inline jujugui/static/gui/src/app/app.js]: Thanks, much better.

File: jujugui/static/gui/src/app/app.js (hunk 2 above)
Comment (huwshimi) [inline jujugui/static/gui/src/app/app.js]: Much cleaner.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6817/

File: jujugui/static/gui/src/app/app.js [hunk 3]
```diff
@@ -1230,7 +1230,7 @@ YUI.add('juju-gui', function(Y) {
       const env = this.env;
       const db = this.db;
       const connected = this.env.get('connected');
```
Comment (Lukewh) [inline jujugui/static/gui/src/app/app.js]: `connected` only seems to be used on line 1328 maybe just move the `this.env.get('connected')` to there? (I may have missed a usage?

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Build failed: Attempt to land pull request failed
        build url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge/2136

**Comment by frankban** [comment]
Conflicts must be solved before landing this branch.

**Comment by jujugui** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://ci-cge.jujugui.org:8080//job/juju-gui/6829/

**Comment by huwshimi** [comment]
Let's try this again :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci-gce.jujugui.org:8080/job/juju-gui-merge
