### PR TITLE
Fix usso no models

### LINKED ISSUE #2012: Logging in via USSO to a controller with no models does not load canvas
To reproduce, bootstrap a new controller with the following:

```
juju bootstrap aws aws --credential admin --config identity-url=https://api.jujucharms.com/identity
juju grant everyone@external addmodel
```
Where 'admin' is whatever you've named your credentials. This can also be done on any provider not just aws as listed.

Then build the latest tip of GUI and `upgrade-gui`
Once the GUI loads, click to log in via USSO. 
You'll notice that once that successfully completes the GUI never renders the canvas to drop the user into the unconnected state, even though the console says otherwise.

### PR DESCRIPTION
**Pull request by hatched**
When connecting via JIMM it's possible that the user has no models. This makes sure that we drop that user into the unconnected state upon logging into the GUI via USSO.

Fixes #2012

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA

Start the GUI locally using `make run`
Update the development.ini
Log in via USSO
You should get the canvas.

Make sure the GUI still works properly in Juju 2 using normal dist and u/p as well.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5881/
Test PASSed.

File: jujugui/static/gui/src/app/app.js [hunk 1]
```diff
@@ -736,6 +736,7 @@ YUI.add('juju-gui', function(Y) {
           if (modelList.length === 0) {
             // XXX Drop the user into the uncommitted state.
```
Comment (frankban) [inline jujugui/static/gui/src/app/app.js]: You can remove this XXX now.

Comment (hatched) [inline jujugui/static/gui/src/app/app.js]: done!

**Comment by hatched** [comment]
Thanks @frankban 

:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5889/
Test PASSed.
