### PR TITLE
Fix uncommitted state on destroyed services.

### LINKED ISSUE #1740: Destroyed service on canvas is not uncommitted
When destroying a deployed service, the service block on the canvas does not represent a uncommitted state. The only way to see what is destroyed is to check the commit log.

### PR DESCRIPTION
**Pull request by kadams54**
Fixes #1740.

### CODE REVIEW

**Comment by kadams54** [comment]
## QA

1. Deploy a service and commit the changes.
2. Destroy the service.
3. Verify that it goes back into an uncommitted (light blue) state on the canvas.
4. Check other service states, e.g., pending, to verify that they also work.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5790/
Test PASSed.

**Comment by frankban** [comment]
Code looks good, thanks!

File: jujugui/static/gui/src/app/views/topology/service.js [hunk 1]
```diff
@@ -189,6 +189,7 @@ YUI.add('juju-topology-service', function(Y) {
           'stroke': '#19b6ee',
```
Comment (kadams54) [inline jujugui/static/gui/src/app/views/topology/service.js]: Need to retain this as it apparently sets the stroke color when the charm is initially added to the canvas. Without this line, the charm will just have a normal grey stroke when first added.

Comment (hatched) [inline jujugui/static/gui/src/app/views/topology/service.js]: Can you add code comments to this effect for this and the one above so that we don't have to investigate this again in the future.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5794/
Test PASSed.

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge
