### PR TITLE
Fix comma in machine details

### LINKED ISSUE #2059: Errant comma in DF
screen shot 2016-09-30 at 13 58 14

### PR DESCRIPTION
**Pull request by huwshimi**
Fixes #2059.

### CODE REVIEW

**Comment by huwshimi** [comment]
QA:
- add a service
- open the deployment flow
- the machine in the machines section should be something like "trusty (constraints not set)" with no comma after the series.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/5917/
Test PASSed.

File: jujugui/static/gui/src/app/components/deployment-flow/machines/machines.js [hunk 1]
```diff
@@ -42,27 +42,26 @@ YUI.add('deployment-machines', function() {
...
           disk = disk / 1024;
           mem = mem / 1024;
           constraintsDetails = `${cores}x${cpu}GHz, ${mem.toFixed(2)}GB, ` +
             `${disk.toFixed(2)}GB`;
-        } else {
-          constraintsDetails = '(constraints not set)';
         }
         if (series) {
-          seriesDetails = `${series}, `;
+          parts.push(`${series}${constraintsDetails ? ',' : ''}`);
```
Comment (hatched) [inline jujugui/static/gui/src/app/components/deployment-flow/machines/machines.js]: Instead of doing this could you instead do:

```JavaScript
if (series) {
  parts.push(series);
}
parts.push(constraintsDetails || '(constraints not set)');
const info = parts.join(', ');
```

Comment (huwshimi) [inline jujugui/static/gui/src/app/components/deployment-flow/machines/machines.js]: Won't that mean we always have the comma? The idea with this branch is that we only sometimes need the comma.

Comment (hatched) [inline jujugui/static/gui/src/app/components/deployment-flow/machines/machines.js]: join will only put a comma between values:
```

< ['a', 'b', 'c'].join(', ')
> "a, b, c"
< [].join(', ')
> ""
```

Comment (hatched) [inline jujugui/static/gui/src/app/components/deployment-flow/machines/machines.js]: Sorry, ignore what I said - my comments don't fix the associated bug :)

**Comment by hatched** [comment]
:shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge
