### PR TITLE
Applications with resources now get deployed with them

### LINKED ISSUE #2166: We should list resources when adding a charm
GUI doesn't deploy charms when they have resources. Deploying "kubernetes-core" for example fails with GUI, but works with CLI. The proper way to add a charm is to list resources with it. Check out code for conjure-up:
https://github.com/conjure-up/conjure-up/blob/master/conjureup/juju.py#L385-L403

### PR DESCRIPTION
**Pull request by hatched**
When deploying an application that has resources in the charm store we need to call a Juju api method `addPendingResources` prior to deploy to make Juju know about these resources.

Fixes #2166

### CODE REVIEW

**Comment by hatched** [comment]
#### To QA
- Deploy the kubernetes-core bundle, it should deploy as expected.
- In a new model deploy a single non-resources charm, it should deploy as expected.
- In a new model deploy a single charm with resources (easyrsa works), it should deploy as expected.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6164/
Test PASSed.

File: jujugui/static/gui/src/app/store/env/api.js [hunk 1]
```diff
@@ -1200,6 +1200,20 @@ YUI.add('juju-env-api', function(Y) {
         return;
       }
       const ecs = this.get('ecs');
+      if (args.charmResources) {
```
Comment (frankban) [inline jujugui/static/gui/src/app/store/env/api.js]: I think callers have the responsibility to do this, and injecting an extraneous deploy argument like this can be confusing.

File: jujugui/static/gui/src/app/utils/environment-change-set.js [hunk 2]
```diff
@@ -592,6 +592,18 @@ YUI.add('environment-change-set', function(Y) {
     },
 
     /**
+      Creates a new entry in the queue to add the pending resources.
+      @param {Array} The arguments to add the pending resources with.
+    */
+    _lazyAddPendingResources: function(args) {
```
Comment (frankban) [inline jujugui/static/gui/src/app/utils/environment-change-set.js]: Where are we collecting the response for this call?

Comment (hatched) [inline jujugui/static/gui/src/app/utils/environment-change-set.js]: We aren't, it didn't appear to be necessary.

File: jujugui/static/gui/src/app/store/env/api.js (hunk 1 above)
Comment (hatched) [inline jujugui/static/gui/src/app/store/env/api.js]: Originally I was thinking the same but ended up this way. I can revert back.

**Comment by jujugui** [comment]
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6169/
Test FAILed.

**Comment by jujugui** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://ci.jujugui.org:8080//job/juju-gui/6171/
Test PASSed.

File: jujugui/static/gui/src/app/utils/environment-change-set.js [hunk 3]
```diff
@@ -638,6 +661,11 @@ YUI.add('environment-change-set', function(Y) {
               delete config[key];
             }
           });
+          // Check if we have any resources, if we do, then add them.
+          const resourceIds = ghostService.get('resourceIds');
```
Comment (frankban) [inline jujugui/static/gui/src/app/utils/environment-change-set.js]: Having one call executed after the other without the need for storing the pending ids in a state would have been better, but I understand that this may require changes in the ecs we don't want to do now. Are we sure this little state here will be cleaned up later? I guess the whole ghost service will be destroyed after firing the ecs.

Comment (hatched) [inline jujugui/static/gui/src/app/utils/environment-change-set.js]: I didn't have any plans on removing this. All other commands which change records have updated the corresponding record in the model. While this is adding a new record I don't think that it is to far from the conventions we've set forward. I actually think it would have been worse to create some kind of an internal ecs database to store this as we'd then have to make sure that never got out of sync.

**Comment by hatched** [comment]
Thanks for the review @frankban were you also able to do a QA?

**Comment by urosj** [comment]
QA 👍

**Comment by hatched** [comment]
Thanks all! :shipit:

**Comment by jujugui** [comment]
Status: merge request accepted. Url: http://ci.jujugui.org:8080/job/juju-gui-merge
